### ISSUE TITLE
Duplication / Mirroring of Joints

### ISSUE THREAD

**Issue by rosskouk** [mwganson/joint#7]
Hi @mwganson,

Thanks for sharing this macro, it definitely saves a lot of time!  I'm having an issue when creating a ball joint, I select the face I want to place the joint on, and the ball joint is created, however it also creates a mirror of the ball joint that goes through the face I selected.  This wasn't the behaviour I expected and I'm wondering if you can assist or point me in the right direction.  The picture below shows what is happening.

![image](https://github.com/mwganson/joint/assets/49451758/8fca9202-e54b-4002-a990-346c9aac0183)

The ball joint on the outer face is exactly what I want, but when it's created another ball joint appears that does through the face and into the enclosure.

Thanks

**Comment by rosskouk** [comment]
I've managed to sort it out, solved by setting symmetric to false and reversed to true in the positioning properties!  Thanks again for a fantastic macro!

**Comment by mwganson** [comment]
Glad you figured it out.  This is actually by design.  As in your case, the reversed property was needed.  With your model it's easy to see that the joint needed to be reversed, but if the inner wall was solid and the joint was embedded you might have gotten the impression the joint macro had utterly failed to produce anything.  So, I made the decision to make the symmetric property true by default so that way at least the user always saw something on the screen.  "Okay, so this is working, sort of, I just need to sort out what's going on here."  Instead of, "This thing didn't too anything."

Some tweaking of the properties will always be needed, anyway.  The default size will almost never be the desired size, for example.  And you might often need to tweak the positioning or experiment with the offset to get the desired fit.
